# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmplint" do
  name "cmplint"
  desc "cmplint is a Go static analysis tool (linter) that detects unnecessary or potentially incorrect usage of pointers to zero-sized types."
  homepage "https://github.com/fillmore-labs/cmplint"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmplint"
  depends_on formula: [
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/fillmore-labs/cmplint/releases/download/v#{version}/cmplint_darwin_amd64.tar.gz"
      sha256 "e38015e8fee1d417a1cb916465b0eb12a95e0e51ab0a57734bdc654dc7aa6e3c"
    end
    on_arm do
      url "https://github.com/fillmore-labs/cmplint/releases/download/v#{version}/cmplint_darwin_arm64.tar.gz"
      sha256 "d6b83a893b0915b17915a7efa0de417b6e980f0f187f07da21dfc8536742734f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fillmore-labs/cmplint/releases/download/v#{version}/cmplint_linux_amd64.tar.gz"
      sha256 "6e89a7bca7931cebfa2f5c7dbb8ea1b9f8e25c77172a8dbac262aa607cf1e633"
    end
    on_arm do
      url "https://github.com/fillmore-labs/cmplint/releases/download/v#{version}/cmplint_linux_arm64.tar.gz"
      sha256 "7abc8c74dde48ede5ea4e970950acd4f42664cf214b39d48bf90cf5db5f2ffc9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/cmplint"]
    end
  end

  # No zap stanza required
end
