# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmplint" do
  desc "cmplint is a Go static analysis tool (linter) that detects unnecessary or potentially incorrect usage of pointers to zero-sized types."
  homepage "https://github.com/fillmore-labs/cmplint"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmplint"
  depends_on formula: [
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/fillmore-labs/cmplint/releases/download/v0.0.4/cmplint_darwin_amd64.tar.gz"
      sha256 "165c2eb6b136dcf3e45a08324114322acf39e773dbb8f38a752fb811999fb147"
    end
    on_arm do
      url "https://github.com/fillmore-labs/cmplint/releases/download/v0.0.4/cmplint_darwin_arm64.tar.gz"
      sha256 "c616177faeff577c390f4d6c58be3a64532cae18d1d3c675acc4e2afe2afc27b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fillmore-labs/cmplint/releases/download/v0.0.4/cmplint_linux_amd64.tar.gz"
      sha256 "dcc36ea10838d41104fb8443b0924e611a59db4e47613a333e4cec44268512b4"
    end
    on_arm do
      url "https://github.com/fillmore-labs/cmplint/releases/download/v0.0.4/cmplint_linux_arm64.tar.gz"
      sha256 "7d633af9099d973e55f952333e76038109c04f004cd5c73c80b2d73df441e608"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/cmplint"]
    end
  end

  # No zap stanza required
end
