# This file was generated by GoReleaser. DO NOT EDIT.
cask "errortype" do
  desc "errortype is a Go static analysis tool (linter) that detects inconsistent usage of custom error types as pointers versus values."
  homepage "https://github.com/fillmore-labs/errortype"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "errortype"
  depends_on formula: [
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/fillmore-labs/errortype/releases/download/v0.0.1/errortype_darwin_amd64.tar.gz"
      sha256 "98e9c5646208336332373f38f6f4653e923296d1633920ba36faac101ced0c4a"
    end
    on_arm do
      url "https://github.com/fillmore-labs/errortype/releases/download/v0.0.1/errortype_darwin_arm64.tar.gz"
      sha256 "c6d92c537be9a6127ae4565041114d66afc07679bc8549306cfa787a8895b736"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fillmore-labs/errortype/releases/download/v0.0.1/errortype_linux_amd64.tar.gz"
      sha256 "7e525b68497ecf1e458cdb2d42b2f4589046eecb83a60113a042214f96eec6ac"
    end
    on_arm do
      url "https://github.com/fillmore-labs/errortype/releases/download/v0.0.1/errortype_linux_arm64.tar.gz"
      sha256 "a3213e7c8bed44fd51cf309527504b0fbce25529fce8050ec7bdcab52790e069"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/errortype"]
    end
  end

  # No zap stanza required
end
