# This file was generated by GoReleaser. DO NOT EDIT.
cask "errortype" do
  name "errortype"
  desc "errortype is a Go static analysis tool (linter) that detects inconsistent usage of custom error types as pointers versus values."
  homepage "https://github.com/fillmore-labs/errortype"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "errortype"
  depends_on formula: [
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/fillmore-labs/errortype/releases/download/v#{version}/errortype_darwin_amd64.tar.gz"
      sha256 "67ce2445e35ec5182879af8f409d01371ab07d7cc6a48cd549a59d48234f1329"
    end
    on_arm do
      url "https://github.com/fillmore-labs/errortype/releases/download/v#{version}/errortype_darwin_arm64.tar.gz"
      sha256 "c5d7e89ab9372a4833192dd925aadfd88908c21d602fb198735d1ee5e16f703b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fillmore-labs/errortype/releases/download/v#{version}/errortype_linux_amd64.tar.gz"
      sha256 "1218ccbe8dcbdc739d704b8bee097b2993bb607a58b6e25e5f38c81e4ee39398"
    end
    on_arm do
      url "https://github.com/fillmore-labs/errortype/releases/download/v#{version}/errortype_linux_arm64.tar.gz"
      sha256 "a11d718cb90af4897ebae7118cb676877a299c154443f549d662549796d5ba2b"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/errortype"]
    end
  end

  # No zap stanza required
end
