# This file was generated by GoReleaser. DO NOT EDIT.
cask "errortype" do
  desc "errortype is a Go static analysis tool (linter) that detects inconsistent usage of custom error types as pointers versus values."
  homepage "https://github.com/fillmore-labs/errortype"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "errortype"
  depends_on formula: [
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/fillmore-labs/errortype/releases/download/v0.0.3/errortype_darwin_amd64.tar.gz"
      sha256 "8ecd606cae4dab727b56ba83e513ebea1a121e4fae0a57699cbea26c7c4fc7b3"
    end
    on_arm do
      url "https://github.com/fillmore-labs/errortype/releases/download/v0.0.3/errortype_darwin_arm64.tar.gz"
      sha256 "921cf98a95380a29257023fae8593ceefb197e254b38466a70f7ebea24bd0dd6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fillmore-labs/errortype/releases/download/v0.0.3/errortype_linux_amd64.tar.gz"
      sha256 "1d4fc830f7b07af2e1b39bd222e5baad5776b2355e76337c25074580396d10ee"
    end
    on_arm do
      url "https://github.com/fillmore-labs/errortype/releases/download/v0.0.3/errortype_linux_arm64.tar.gz"
      sha256 "ec16226a5e845ccbc5bd1889b968a1b8b2b27b23bbee40a84f7eb26193309802"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/errortype"]
    end
  end

  # No zap stanza required
end
