# This file was generated by GoReleaser. DO NOT EDIT.
cask "scopeguard" do
  name "scopeguard"
  desc "scopeguard Go static analyzer that identifies variables with unnecessarily wide scope and suggests moving them to tighter scopes."
  homepage "https://github.com/fillmore-labs/scopeguard"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scopeguard"
  depends_on formula: [
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/fillmore-labs/scopeguard/releases/download/v#{version}/scopeguard_darwin_amd64.tar.gz"
      sha256 "70a358d1daea16881589127a8e1b257dc0ff71a84d6830576693fb436dde3698"
    end
    on_arm do
      url "https://github.com/fillmore-labs/scopeguard/releases/download/v#{version}/scopeguard_darwin_arm64.tar.gz"
      sha256 "30235c806be120d10bca78073a8e384eb32fc2659e927aab3d5a8fc82f3b5ab5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fillmore-labs/scopeguard/releases/download/v#{version}/scopeguard_linux_amd64.tar.gz"
      sha256 "94e3855c5f1724a58b004484f0971784ee9c7c633b93e46bdf9b9d89a6972e93"
    end
    on_arm do
      url "https://github.com/fillmore-labs/scopeguard/releases/download/v#{version}/scopeguard_linux_arm64.tar.gz"
      sha256 "b3bddf10f3c75732ac1c206d10f2d800573d2936edc617c6f3b810c145539cd0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/scopeguard"]
    end
  end

  # No zap stanza required
end
