# This file was generated by GoReleaser. DO NOT EDIT.
cask "zerolint" do
  name "zerolint"
  desc "zerolint is a Go static analysis tool (linter) that detects unnecessary or potentially incorrect usage of pointers to zero-sized types."
  homepage "https://github.com/fillmore-labs/zerolint"
  version "0.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zerolint"
  depends_on formula: [
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/fillmore-labs/zerolint/releases/download/v#{version}/zerolint_darwin_amd64.tar.gz"
      sha256 "d816b9309af1217ae5eb16f3daec71bac2078a0221dfa2d444e7d81bfa0d3ecd"
    end
    on_arm do
      url "https://github.com/fillmore-labs/zerolint/releases/download/v#{version}/zerolint_darwin_arm64.tar.gz"
      sha256 "298af773a27e25146c0a717b4e5ddbc5babfe034eb5392ece034b8c48c7835cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fillmore-labs/zerolint/releases/download/v#{version}/zerolint_linux_amd64.tar.gz"
      sha256 "b85b61f09be793661b0627c793476468ecf9c6ab737a8e7d7472b0cf18c408af"
    end
    on_arm do
      url "https://github.com/fillmore-labs/zerolint/releases/download/v#{version}/zerolint_linux_arm64.tar.gz"
      sha256 "cbb001b501f017a0413e9bd709855bbe6c583f323edb4c2d45bb1dec0fb6936f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/zerolint"]
    end
  end

  # No zap stanza required
end
