# This file was generated by GoReleaser. DO NOT EDIT.
cask "zerolint" do
  name "zerolint"
  desc "zerolint is a Go static analysis tool (linter) that detects unnecessary or potentially incorrect usage of pointers to zero-sized types."
  homepage "https://github.com/fillmore-labs/zerolint"
  version "0.0.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zerolint"
  depends_on formula: [
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/fillmore-labs/zerolint/releases/download/v#{version}/zerolint_darwin_amd64.tar.gz"
      sha256 "810d7c0264741ccbb587316adffe875461ac7e287fb33d0ac8df2f7b11b9ac2e"
    end
    on_arm do
      url "https://github.com/fillmore-labs/zerolint/releases/download/v#{version}/zerolint_darwin_arm64.tar.gz"
      sha256 "d4b3fe51730053f9880cce558df1d0d16c531cf79ec67661b7e3d2b00b285f6c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fillmore-labs/zerolint/releases/download/v#{version}/zerolint_linux_amd64.tar.gz"
      sha256 "98c4f095817ea3d5537803bb1c3b23e42eba30eb295dc4e54ff14558b802a5e3"
    end
    on_arm do
      url "https://github.com/fillmore-labs/zerolint/releases/download/v#{version}/zerolint_linux_arm64.tar.gz"
      sha256 "c6eaff80be4e151f472197e6c68c70b484ab43fa84556db06ac2af651de3267a"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/zerolint"]
    end
  end

  # No zap stanza required
end
